---
- name: Include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', findme) }}"
  vars:
    findme:
      paths:
        - "vars"
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true

# Setup config before installing chrony to keep idempotency.
# Installing the service will also start it, but we want chrony to run with OUR config.
# If we install chrony before installing the config file, chrony would have to be restarted and we'd lose idempotency.
- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ chrony_config_file | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set up
  ansible.builtin.template:
    src: templates/chrony.conf.j2
    dest: "{{ chrony_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart chrony

- name: Create systemd drop-in
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ chrony_service_name }}.service.d"
    owner: root
    group: root
    mode: 0644

- name: Set up systemd override
  ansible.builtin.template:
    src: "templates/systemd_override.conf.j2"
    dest: "/etc/systemd/system/{{ chrony_service_name }}.service.d/override.conf"
    owner: root
    group: root
    mode: 0755

- name: Install
  ansible.builtin.package:
    name: "chrony"
    state: present

- name: Disable conflicting services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  register: disable_service_result
  failed_when: (disable_service_result is failed)
               and ('Could not find the requested service' not in disable_service_result.msg)
  loop:
    - ntpd
    - systemd-timesyncd

- name: Start service
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    state: started

- name: Enable service
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    enabled: true
...
